apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-testui-service
  labels:
    app: {{ .Values.testui.label.name }}
spec:
  ports:
  - name: tcp
    port: {{ .Values.testui.service.port }}
    protocol: TCP
    targetPort: {{ .Values.testui.container.port }}
  selector:
    app: {{ .Values.testui.label.name }}
  type: {{ .Values.testui.service.type }}